# Generated by Django 3.2.8 on 2021-10-21 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='profilephoto/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Article',
            new_name='FreeArticle',
        ),
        migrations.CreateModel(
            name='ProCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='course/')),
                ('price', models.FloatField(default=0.0)),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datawork.author')),
            ],
        ),
    ]
