# Generated by Django 3.2.8 on 2021-10-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0004_alter_freearticle_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freearticle',
            name='images',
        ),
    ]
