# Generated by Django 3.2.8 on 2021-10-31 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0007_orderedcourses_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedcourses',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datawork.procourses'),
        ),
    ]
